import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import Horizon from "@/app/lib/component/navigate";
import Image from "next/image";

const archivo = Archivo({ subsets: ["latin"], weight: "100" });

export const metadata: Metadata = {
  title: "penwell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="pen.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={archivo.className}
        style={{
          margin: 0,
          padding: 0,
          minWidth: "1366px",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
          }}
        >
          <Horizon />
          <div
            style={{
              filter: "grayscale(60%)",
              zIndex: "-1",
              opacity: "0.8",
              display: "flex",
              flexDirection: "column",
              position: "absolute",
            }}
          >
            <Image
              src="/7657406.jpg"
              alt="pexels-7657406"
              width={1366}
              height={2048}
              priority={true}
            />
          </div>
            <footer
              style={{
                color: "#ececec",
                fontSize: "32px",
                fontFamily: "Josefin Sans",
                backgroundColor: "#0087af",
                userSelect: "none",
                minHeight: "256px",
                position: "fixed",
                padding: "32px",
                bottom: 0,
                right: 0,
              }}
            >
              <p>PenWell,WriteWell</p>
              <p>© 2023</p>
            </footer>
          <div
            style={{
              height: "60%",
            }}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
